language: rust
sudo: false
rust:
- stable
- nightly
- beta
matrix:
  include:
  - rust: nightly
    env: FEATURES="unstable"
script: |
  cargo build --verbose --features "${FEATURES}"
  cargo test --verbose --features "${FEATURES}"
